name:                types-as-specifications
version:             0.1.0.0
github:              "githubuser/types-as-specifications"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/types-as-specifications#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- row-types
- indexed
- indexed-extras
- ghcid

library:
  source-dirs: src

executables:
  types-as-specifications-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    dependencies:
    - types-as-specifications

tests:
  types-as-specifications-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - types-as-specifications
